site:
  baseline: 'Food and soul '
  baseurl: /
  canonicalurl: true
  date:
    format: j F Y
    timezone: Europe/Paris
  description: 'A starter blog, powered by Cecil and Netlify CMS.'
  netlify:
    cms:
      path: admin
      version: latest
    identity:
      version: v1
  pagination:
    max: 5
    path: page
  title: Starter blog
theme: hyde
